version: "3.9"

services:
  wa-sticker-bot:
    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: wa-sticker-bot

    restart: unless-stopped

    shm_size: "512m"

    environment:
      NODE_ENV: production
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium

    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./temp:/app/temp

    security_opt:
      - seccomp:unconfined
